### ISSUE TITLE
Mundane containers weight lost on collapse

### ISSUE THREAD

**Issue by grapeape69ca** [bmos/FG-PFRPG-Extraplanar-Containers#10]
Backpacks and pouches, not nested, have their contents' weight subtracted from Encumbrance Current Weight (5e) when collapsed.  Re-expanding adds the weight back to Current.

**Comment by bmos** [comment]
Fixed in https://github.com/bmos/FG-CoreRPG-Extraplanar-Containers/releases/tag/v1.12-hotfix.3.
Thanks!
