### ISSUE TITLE
Non-collapsed mundane inside collapsed extraplanar show contents under extraplanar

### ISSUE THREAD

**Issue by grapeape69ca** [bmos/FG-PFRPG-Extraplanar-Containers#11]
Non-collapsed mundane inside collapsed extraplanar show contents under extraplanar.  This is probably similar to #5.  But, I was thinking maybe it's possible to check the contents of an extraplanar for mundanes and collapse them when double-click trigger on extraplanar happens.  This would just be a nice to have, players can manually collapse mundanes inside an extraplanar before collapsing the extraplanar to avoid what looks like the mundane's contents getting dumped to main inventory; they are nested and do look to be nested under the collapsed extraplanar anyhow.

**Comment by bmos** [comment]
Does stacking mundane in extraplanar even work? I assumed it would be counting the weight of the child container... If it does work I'll look into fixing this.

**Comment by grapeape69ca** [comment]
![boh-mundane-nesting](https://user-images.githubusercontent.com/16261780/192142628-07a2f948-4a75-4992-81f8-dcaee670e8af.JPG)

Yes, it works.  The total current encumbrance changes when mundane bags are moved in/out of the extraplanar (5e).

As you can see from the screenshot if Pouch 2 isn't collapsed before the Bag of Holding is collapsed, it's contents appear to "spill" into main inventory, but they are indented as if the Bag of Holding isn't collapsed and stay at the location in inventory as if the extraplanar isn't collapsed.

I also noted while testing this that prefixing the container with [+] makes adding items to it need you to type the [+]... in the location column to find the bag.  Would it still work if the [+] was moved to the suffix? Maybe this should be a separate bug ticket?

**Comment by bmos** [comment]
Suffix wouldn't change anything. Location needs to be identical for the program to recognize the match.

It's not a problem when it's working, because the invisible contents are... invisible.

**Comment by bmos** [comment]
because of how FG's lua code implementation works, I can't have it search through all hierarchies of containers.
but i can search a specific number of hierarchies.
for now, it's one additional layer of depth, since that was your example.

**Comment by grapeape69ca** [comment]
> Suffix wouldn't change anything. Location needs to be identical for the program to recognize the match.
> 
> It's not a problem when it's working, because the invisible contents are... invisible.

But if I try to add an item to "Pouch 2" from top level inventory it doesn't find it because it's "[+] Pouch 2" and the pattern matching is from start of name.  But, you're right, players can deal with it by first expanding the container then adding items to it.

**Comment by grapeape69ca** [comment]
> because of how FG's lua code implementation works, I can't have it search through all hierarchies of containers. but i can search a specific number of hierarchies. for now, it's one additional layer of depth, since that was your example. [4d94fcf](https://github.com/bmos/FG-CoreRPG-Extraplanar-Containers/commit/4d94fcfc68a7bf5d343fcd7905d14da964e42c50)

Awesome thanks!

**Comment by bmos** [comment]
> > Suffix wouldn't change anything. Location needs to be identical for the program to recognize the match.
> > It's not a problem when it's working, because the invisible contents are... invisible.
> 
> But if I try to add an item to "Pouch 2" from top level inventory it doesn't find it because it's "[+] Pouch 2" and the pattern matching is from start of name. But, you're right, players can deal with it by first expanding the container then adding items to it.

Ah, now I see what you mean.
I can look into that more in the future.
