### ISSUE TITLE
Long content's weight total cause digit clipping

### ISSUE THREAD

**Issue by grapeape69ca** [bmos/FG-PFRPG-Extraplanar-Containers#12]
![bag-of-holding](https://user-images.githubusercontent.com/16261780/192098890-a43a74ba-3b30-4454-947e-ae12fded8ea3.jpg)

The width of the container's contents weight field can clip digits, and make the weight hard to read, if the number is great enough (see jpg).

**Comment by bmos** [comment]
Ah, I'll trim decimals based on length.
