### ISSUE TITLE
Locating overweight containers?

### ISSUE THREAD

**Issue by rushl** [bmos/FG-PFRPG-Extraplanar-Containers#14]
Is it possible to run a command to locate all the overweight containers? As far as I can tell, right now that check is only triggered (and a message to chat is sent) when the items in a container goes from underweight to overweight. It would be great if I could locate all the containers overweight at once, or perhaps have each container checked when the character sheet or inventory is opened?

Thanks!

**Comment by bmos** [comment]
What if I just color the names or weights of overweight containers in red?

**Comment by rushl** [comment]
Oh, I think that would be great! Just something where you could go through and see if anything needs adjusting. Thanks!

**Comment by bmos** [comment]
Awesome. I have created that feature and it is [sitting in the "test" branch](https://github.com/bmos/FG-CoreRPG-Extraplanar-Containers/commit/d8582506a27cddca12be80c4828f66e88df306ac).
This branch will be published along with the upcoming FG ruleset changes in mid/late Feb.
It also gives the "weight" field a tooltip to clarify whether it's overweight or overvolume.
