### ISSUE TITLE
Option to Limit by item count?

### ISSUE THREAD

**Issue by rushl** [bmos/FG-PFRPG-Extraplanar-Containers#15]
Would you consider adding the option to limit the container to an item count (in addition to the existing weight or volume)? That would make it much easier to use containers for things like scroll pouches or potion bandoliers. There are a _huge_ number of small items that just don't have a weight assigned. It would be so much easier to set an item limit on the container than update dozens and dozens of items (many of which are locked, and you have to make a copy to update it).

Thanks!

**Comment by bmos** [comment]
That's a cool idea! It's not ideal because 1 scroll and 1 full plate obviously are different, but if used sparingly for things like bandoliers and pouches it would be a useful addition.

**Comment by rushl** [comment]
True, but it would be much easier to spot out-of-place items than to spot 14 items when there should be 12.
