### ISSUE TITLE
Default containers?

### ISSUE THREAD

**Issue by rushl** [bmos/FG-PFRPG-Extraplanar-Containers#17]
This extension greatly improves the item-in-container experience in terms of keeping track of containers and their contents! However, it could also improve the experience of placing items into a container. Specifically, it would be nice to have a "default" container into which all newly added items go. 

Right now, the most difficult part of managing items in containers is now getting them into containers in the first place. Being able to designate a "default" container would really make the inventory system amazing!

**Comment by bmos** [comment]
This seems like the sort of thing that would be better handled by a separate extension.
It would be quite easy to implement.
You'd just need to intercept ItemManager.onCharAddEvent(nodeItem) and replace the "location" field with your preferred location.
Of course you might want to have a UI allowing you to pick a container as default which would be more complex but not terrible.
