### ISSUE TITLE
Error when opening inventory

### ISSUE THREAD

**Issue by adamantida** [bmos/FG-PFRPG-Extraplanar-Containers#23]
![image](https://github.com/user-attachments/assets/6a7d75ce-bb12-4572-a70e-4583ab5284a8) 
Faced a problem. Put through forge, created an empty character and opened the inventory.

**Comment by adamantida** [comment]
If anyone has also encountered the error: It doesn't update on forge, or with a delay. download from git

**Comment by bmos** [comment]
Thank you so much for pointing this out. It looks like when I pushed the new release, it did not get to the forge correctly. I will re-release this today.

**Comment by bmos** [comment]
I manually uploaded to the forge for now.
Can you delete your local copy and see if it's fixed?

**Comment by adamantida** [comment]
> I manually uploaded to the forge for now. Can you delete your local copy and see if it's fixed?

Yes, it has updated in forge
