### ISSUE TITLE
Error on extension initialize

### ISSUE THREAD

**Issue by BurcinSayin** [bmos/FG-PFRPG-Extraplanar-Containers#7]
Here is the console log entry
[ERROR]  Script execution error: [string "scripts/extraplanarcontainers.lua"]:258: attempt to index global 'CharEncumbranceManager' (a nil value)

it seems like "CharEncumbranceManager" is deprecated or invalid

**Comment by bmos** [comment]
The code you are looking at is for [v1.8](https://github.com/bmos/FG-CoreRPG-Extraplanar-Containers/releases/tag/v1.8-rc.1) which is for the new ruleset update that is to be released in the next few days.
Are you seeing this error in FG when installing from the Forge? It is possible I have pushed v1.8 to live accidentally?

**Comment by BurcinSayin** [comment]
Ah sorry for the inconvenience. You live version ( forge ) was ok. I saw the error while using the git version.

**Comment by bmos** [comment]
What a relief! In the future I'll try and keep test code on test branches!
Thanks for your work on this PR.
